on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: 0x150/attestest

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - id: current-time
        run: echo "UNIX_TIME=$(date +%s)" >> $GITHUB_OUTPUT

      - id: build-and-push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.current-time.outputs.UNIX_TIME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-name: index.docker.io/${{ env.IMAGE_NAME }}
      #     subject-digest: ${{ steps.build-and-push.outputs.digest }}
      #     push-to-registry: true
